mysql:
  container_name: wander_mysql
  image: mysql:latest
  entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root